### PR TITLE
fix: Support tag values containing `=`

### LINKED ISSUE #14: `=`s within `reply-parent-msg-body` on `privmsg`s cause the parser to break early
To reproduce, send a `privmsg` as `foo=bar`, then reply to that `privmsg`. `reply-parent-msg-body` in the reply's tags,  will only show `foo`.

### PR DESCRIPTION
**Pull request by KararTY**
Fixes #14

### CODE REVIEW

**Comment by KararTY** [comment]
@brian6932 review requested! 1x

File: lib/message/parser/tags.ts [hunk 1]
```diff
@@ -27,12 +27,13 @@ export function parseTags(tagsSrc: string | undefined): IRCMessageTags {
   }
 
   for (const tagSrc of tagsSrc.split(";")) {
-    let key: string;
-    let valueSrc: string | undefined;
+    const key = tagSrc.split("=").shift() as string;
```
Comment (brian6932) [inline lib/message/parser/tags.ts]:
```suggestion
```
Avoid looping this for the 3rd-4th time. V8 `shift()` Aware.

File: lib/message/parser/tags.ts [hunk 2]
```diff
@@ -27,12 +27,13 @@ export function parseTags(tagsSrc: string | undefined): IRCMessageTags {
...
 
-    // eslint is bugged on this in the current version
-    // eslint-disable-next-line prefer-const
-    [key, valueSrc] = tagSrc.split("=", 2);
+    let valueSrc;
+    const indexOfFirstSeparator = tagSrc.indexOf("=");
+    if (indexOfFirstSeparator !== -1) {
+      valueSrc = tagSrc.slice(indexOfFirstSeparator + 1);
+    }
```
Comment (brian6932) [inline lib/message/parser/tags.ts:36]:
```suggestion
    const indexOfFirstSeparator: number = tagSrc.indexOf("=");

    if (indexOfFirstSeparator === -1) continue;

    const key: string = tagSrc.slice(0, indexOfFirstSeparator),
      valueSrc: string = tagSrc.slice(indexOfFirstSeparator + 1);

    tags[key.toLowerCase()] = decodeValue(valueSrc);
```

File: lib/message/parser/tags.ts [hunk 3]
```diff
@@ -27,12 +27,13 @@ export function parseTags(tagsSrc: string | undefined): IRCMessageTags {
...
 
     tags[key.toLowerCase()] = decodeValue(valueSrc);
```
Comment (brian6932) [inline lib/message/parser/tags.ts:38]:
```suggestion
```

**Review by brian6932 — CHANGES_REQUESTED** [review]
something like this

File: lib/message/parser/tags.ts (hunk 3 above)
Comment (brian6932) [inline lib/message/parser/tags.ts]:
```suggestion
    const keyValueDelimiter: number = tagSrc.indexOf("=");

    tags[tagSrc.slice(0, keyValueDelimiter)] =
      keyValueDelimiter === -1
        ? null
        : decodeValue(tagSrc.slice(keyValueDelimiter + 1));
```
From reading the code, and checking tags, this is what came to mind, `toLowerCase()` was removed as tags are always lowercase. I'm not really positive on why a check for no `=` was here in the first place, OGProdigy mentioned that it's apart of the spec, but doesn't seem to be used, so maybe it should be removed, I'll ask randers for more info when I get the chance.
_blame prettier for the fugly formatting_


After looking at this parser, some future PR ideas come to mind:
- Removing the branch in `decodeValue()`, as we do it in `parseTags()` now. Or just removing `decodeValue()` altogether, it's not really needed, we can do all the logic in `parseTags()` (tests will have to be updated, either way).
- Using the buffer directly, and `toString()`ing tags and their properties.
- Moving to a traditional for loop, slicing indices instead of splitting at all (the above point would make this cleaner as it comes with a `keys()` iterator method).
- Using the `this` binding of `parseTags()` as a constructor function, then instancing with `new`, no need to create an extra object, as it's already a `this` bounded function.

**Review by brian6932 — CHANGES_REQUESTED** [review]

File: lib/message/parser/tags.ts (hunk 3 above)
Comment (KararTY) [reply lib/message/parser/tags.ts]: Thank you, please consider creating issues for those. You're free to take up on implementing them.

File: lib/message/parser/tags.ts (hunk 1 above)
Comment (brian6932) [reply lib/message/parser/tags.ts]: Don't forget to remove this line as well, it's why actions is complaining

**Review by brian6932 — CHANGES_REQUESTED** [review]
